### ISSUE TITLE
WoRMS DwCA

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-repo#11]
The WoRMS DwC archive appears to have some unexpected form. Before contacting them we should pool all spotted problems here and discuss them if needed.

- [ ] **dwc:infraspecificEpithet**: values contain an unexpected rank prefix `var. angustifolia`
- [ ] **circularity**: some name <-> accept name and name <-> parent name relationships between records ultimately constitute an endless loop (see Dicoma kirkii subsp. kirkii)

**Comment by ayco-at-naturalis** [comment]
`Left-to-right: child --> parent
Top-down: name --> accepted name



+--> 1250677 --> 1248065           (--> 1075372 --> 1074891 --> 867905)
|                   |
|                1250719
|                   |
|        +----------+
|        |
|    1250719 --> 1248040           (--> 1075583 --> 1074891 --> 867905)
|                   |
|			    1250677
|			        |
+-------------------+
               `

**Comment by mdoering** [comment]
```
Left-to-right: child --> parent
Top-down: name --> accepted name

+--> 1250677 --> 1248065           (--> 1075372 --> 1074891 --> 867905)
|                   |
|                1250719
|                   |
|        +----------+
|        |
|    1250719 --> 1248040           (--> 1075583 --> 1074891 --> 867905)
|                   |
|                1250677
|                   |
+-------------------+
```

**Comment by mdoering** [comment]
See http://www.marinespecies.org/aphia.php?p=taxdetails&id=1250677 and related
