### ISSUE TITLE
higher classification export

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-repo#2]
The AC 2017 CoL management classification as in use should be exported into a simple dwca and/or ACEF file. Everything down to family level including specie estimates if possible

**Comment by mdoering** [comment]
The ACEF file is missing:
https://raw.githubusercontent.com/Sp2000/colplus-repo/master/ACEF/assembly/1.tar.gz

The DWCA has no content:
https://raw.githubusercontent.com/Sp2000/colplus-repo/master/DWCA/col_management_classification.zip

https://tools.gbif.org/dwca-reports/052-560495488532663712.html

**Comment by ayco-at-naturalis** [comment]
The lowest database_id in the Assembly_Global database currently is 5, so 5.tar.gz is the first ACEF zip file generated

**Comment by mdoering** [comment]
For the management classification we will add https://www.gbif.org/dataset/8067e0a2-a26d-4831-8a1e-21b9118a299c to the dbinit script which should cover the same as http://www.catalogueoflife.org/annual-checklist/2017/details/database/id/500

**Comment by mdoering** [comment]
database_id=500 is the FALO classification.
The current assembly db has a single entry in table _scientific_names_: genus Laminaria
but 5 records in the families table.

Hm, there aint no way to expose those in ACEF.
So I guess we can't do anything at this stage. It feels bad not having the classification in one place and will probably bite us

**Comment by mdoering** [comment]
we should discuss this with Yuri tomorrow

**Comment by mdoering** [comment]
We need to export the current classification from the annual checklist.
If the assembly db doesn't have it we need to take it from the production db down to family

**Comment by mdoering** [comment]
A dwc archive exported from the col prod db with the following columns would be sufficient:
```
taxon_id
name
rank
parent_id
total_species_estimation
estimate_source
```

It should be hosted in this repo and included in the [datasets.sql](https://github.com/Sp2000/colplus-repo/blob/master/ACEF/datasets.sql)

**Comment by mdoering** [comment]
Please create and use new col terms for the species estimates and reference

**Comment by mdoering** [comment]
Looks like a bad data file: https://tools.gbif.org/dwca-reports/179-6899599432424024794.html

**Comment by mdoering** [comment]
Also the export includes genus and species! It should stop at family level

**Comment by ayco-at-naturalis** [comment]
Lower taxa now excluded and higher taxa sort by rank (descending)
