### ISSUE TITLE
ACEF#198 is missing accepted infraspecies

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-repo#20]
There [should be 60 accepted infraspecies for Isoptera](http://www.catalogueoflife.org/col/details/database/id/198) but the [198.tar.gz](https://github.com/Sp2000/colplus-repo/blob/master/ACEF/198.tar.gz) contains 0. I haven't had a chance to investigate why yet. The World Ferns (140.tar.gz) archive has infraspecies, so the bug isn't affecting all exports.

**Comment by mdoering** [comment]
Good to know. Maybe its best to re-export the latest versions, the archives are from 2018 I believe. Still it should have 60 infraspecies: http://www.catalogueoflife.org/annual-checklist/2018/details/database/id/198

**Comment by gdower** [comment]
In the [latest exports](https://github.com/Sp2000/colplus-repo/commit/371661e9dcb7f9d37bd8c0ed238ec607b01df250), ACEF#198 still is affected by this bug and ACEF#204 is also missing all accepted infraspecies, too. ACEF#140 and ACEF#141 have accepted infraspecies. I'll try to fix the issue.
