### ISSUE TITLE
Modify the ACEF exporter to remove name_code prefixes

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-repo#28]
Prefixes were used as namespaces in Assembly_Global to prevent duplicate IDs among GSDs. Removing the namespace prefixes will restore the GSDs' original IDs, making it easier to track records over time.

**Comment by gdower** [comment]
@mdoering, I removed the namespace prefixes from name_code and reference_codes. I need to re-test the ACEF archives, which I'll work on later today.

**Comment by mdoering** [comment]
excellent!
