### ISSUE TITLE
ACEF#7 refers to external species

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-repo#3]
The ACEF file #7 is for common names as I understand:
http://www.catalogueoflife.org/annual-checklist/2017/details/database/id/7

The ACEF file refers to AcceptedSpeciesID which are not present in the file.
That won't work, export needs to include those too

**Comment by mdoering** [comment]
@ayco-at-naturalis can we handle this at all? There is definitely no way the importer can link across different datasets

**Comment by ayco-at-naturalis** [comment]
Interestingly, this happens more often than just with species2000 common naes dataset.
E.g. "aphid wasp" in ITIS Regional (17) points to a species in ITIS Bees (67) - although ITIS Bees itself also contains this common name. So the question is: do we allow cross-dataset links for all common names or just for dataset 7? For now I will assume the latter, and cross-dataset links for common names outside datase 7 will just be bounced by the import program.

**Comment by mdoering** [comment]
The CoL prod site shows ITIS as the source: http://www.catalogueoflife.org/annual-checklist/2017/details/species/id/e935d1a5b98acd3f1a80b5c2cdfae242/common/efe72c987f369543817f5424aa24519e

I am not sure about the purpose of the sp2000 common names dataset. Seems it is to add vernaculars for taxa from other GSDs: http://www.catalogueoflife.org/annual-checklist/2017/details/database/id/7

In such case we should include all scientific names too, even if they are duplicates to some GSDs.
We should ask Yuri and @dimus

**Comment by ayco-at-naturalis** [comment]
special handling for dataset 7 now

**Comment by gdower** [comment]
@ayco-at-naturalis, @mdoering: Just FYI, @yroskov wants to recombine ITIS Bees into ITIS Global, and we want to [eliminate the ACEF#7 dataset](https://github.com/Sp2000/colplus-repo/issues/23), because it has dwindled down to only 18 common names. I plan on recombining ITIS Bees and ITIS Global in our next ITIS update.

**Comment by mdoering** [comment]
@gdower we should really only have a single ITIS dataset with various sectors which Tom Orrell promised to provide as ColDP later in the year. They already do a basic DwC-A, but it's missing essential information like common names and scrutinizer for the CoL. I am in touch with their programmer and Tom was keen to get ITIS updated in the CoL this year so I am confident this will happen. We should not invest much time in additional export work.

**Comment by mdoering** [comment]
thanks for removing number 7!
