### ISSUE TITLE
Remove colons from virus genera

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-repo#30]
Virus names in the CoL do not follow the rules layed out by the ICTV:
https://talk.ictvonline.org/information/w/faq/386/how-to-write-virus-and-species-names

We should strip off at least the colon after the genus name so it becomes a real genus, not a string formatting hack.

**Comment by gdower** [comment]
I asked @yroskov about this and he said the genus isn't supposed to be included in virus names, so that's why CoL included the colon, because they would have had to have significantly refactored the CoL software and database to include virus names. It also makes it possible to [search for viruses by genus and get the number of species in that genus](http://www.catalogueoflife.org/annual-checklist/2019/search/all/key/Alphanecrovirus%3A/fossil/1/match/1).

We could try to remove the colon and see how CoL+ handles it.

**Comment by yroskov** [comment]
Separator between genus name and species polynomial was the only way to present viruses in the CoL in reasonable "shape". Have a look on this example with & without colon: 
"Alphapapillomavirus: Alphapapillomavirus 14 ICTV" vs "Alphapapillomavirus Alphapapillomavirus 14 ICTV".
Virus species name may include Latin name of the species from another kingdom: 
http://www.catalogueoflife.org/annual-checklist/2019/search/all/key/Agrotis+ipsilon/fossil/1/match/1 
If you strip off genus (correct presentation for viruses), it will create another mess such as:
Agrotis ipsilon multiple nucleopolyhedrovirus ICTV (virus species) and
Agrotis ipsilon Hüfnagel, 1766 (moth name)

**Comment by mdoering** [comment]
`Agrotis ipsilon multiple nucleopolyhedrovirus ICTV` is a perfect virus name to me. [CoL+ handles that just fine](http://api.col.plus/parser/name?name=Agrotis%20ipsilon%20multiple%20nucleopolyhedrovirus%20ICTV).

Don't hack the system if there is no need to. We should try to follow the codes.
When did we last time update ICTV by the way? There is a [dwc archive that we could use](https://www.gbif.org/dataset/e01b0cbb-a10a-420c-b5f3-a3b20cc266ad) that is reasonably up to date and which I can easily update as I have generating scripts for it

**Comment by mdoering** [comment]
We try to parse Linnean names into their pieces, but for virus names, hybrid formulas and others that don't fit the system we can handle them simply as a single, unparsable string. This is indicated in the `parsed=true/false` attribute.

**Comment by mdoering** [comment]
The DwC version of ICTV is the latest list from March 2018:
https://dev.col.plus/dataset/2042/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&rank=species&sortBy=taxonomic

It contains 4853 virus species, compared to 3186 species in the AC19 version from 2015

**Comment by mdoering** [comment]
would be good to use immediately after we succeed to build an AC19 catalogue
