### ISSUE TITLE
What to do with duplicate estimates

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-repo#31]
There are quite a few names with multiple species estimate in the database.
Most of them are true duplicates and can be removed.
But others are alternative estimates, e.g. for Protozoa:

```
| 860 | Protozoa | Kingdom | Protozoa |     NULL | Mora C., Tittensor D.P., Adl S., Simpson A.G.B., Worm B. (2011). How Many Species Are There on Earth and in the Ocean? PLoS Biol 9(8): e1001127. doi:10.1371/journal.pbio.1001127 | 2016-03-03 21:58:51 | NULL    |
| 861 | Protozoa | Kingdom | Protozoa |     8118 | Mora C., Tittensor D.P., Adl S., Simpson A.G.B., Worm B. (2011). How Many Species Are There on Earth and in the Ocean? PLoS Biol 9(8): e1001127. doi:10.1371/journal.pbio.1001127 | 2016-03-03 22:00:27 | NULL    |
| 863 | Protozoa | Kingdom | Protozoa |    29000 | Chapman A.D. (2009). Numbers of Living Species in Australia and the World, 2nd edition. ABRS, Australia. 80 p.                                                                    | 2016-03-03 22:16:27 | NULL    |
| 864 | Protozoa | Kingdom | Protozoa |     8118 | Mora C., Tittensor D.P., Adl S., Simpson A.G.B., Worm B. (2011). How Many Species Are There on Earth and in the Ocean? PLoS Biol 9(8): e1001127. doi:10.1371/journal.pbio.1001127 | 2016-03-03 22:18:24 | NULL    |
```

@yroskov @gdower What shall we do with these?
Should we design the system for alternative estimates? It would become a bit complex I reckon

**Comment by gdower** [comment]
@mdoering, I think offering multiple species estimates would be a nice feature to have because the more expert opinions we have, the better we can quantify uncertainty. Having [automatically calculated statistical estimates from species discovery curves](https://rss.onlinelibrary.wiley.com/doi/10.1111/j.1467-9876.2005.00513.x) might be interesting to include eventually, too. If it adds a lot of complexity, then I'd recommend just deleting the duplicates for now and possibly adding it as a feature in the future.

**Comment by mdoering** [comment]
the conplexity is not about storing. We might as well do it now. I just wonder how to make use of multiple estimates e.g when we wanna export, show estimates and percentages in the tree. etc

I gurss we could set a preferref flag or just use the latest

**Comment by gdower** [comment]
Possibly a mean of the species estimates with standard error, that links to a page with a list of all the species estimates and their references/expert name?

**Comment by mdoering** [comment]
we also have a record with name = `Not assigned` in the estimates, Im removing that one

**Comment by mdoering** [comment]
Alright, I am importing all estimates now and allow to attach as many as one likes to a taxon.
@ruud-altenburg I am exporting all of them into AG again and leave the decision what to do with them to the conversion script as it must have been dealing with that already
