### ISSUE TITLE
anonymous authorships in FishBase ACEF files

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-repo#37]
FishBase contains a lot of strange authorships which are flagged as `Unparsable Authorship`:

https://www.col.plus/dataset/1010/verbatim?issue=unparsable%20authorship

> acef:AuthorString 
(Anonymous [Bennett], 1830)
(Anonymous [Lacepède], 1798)
Anonymous [Bennett], 1830
(non [Bennett], 1830)

**Comment by gdower** [comment]
FishBase knows about this and it's because there are no known authors for those species.

**Comment by mdoering** [comment]
But why not just no author? This is garbage and FishBase should not use `Anonymous`, don't you think?

**Comment by yroskov** [comment]
Markus, are we going to teach fish taxonomists on how to do their science? Software should be flexible enough to handle results from various practices as they exist in real science.

**Comment by mdoering** [comment]
well, to some degree yes. I believe we have the responsibility for end users to make sure what we aggregate is consistent and reliable. There are all kinds of ways different communities deal with usually minor issues in different ways. It's obviously a slippery slope. But what are the angular brackets good for in this case? Does that mean anything to a CoL user or will it just confuse him? I will be confused. What is Anonymous supposed to mean here? I don't want to tell Fishbase what to do or how to deal with their data internally. But I don't think this should end up in the Catalogue of Life - unless there is a reason for it we can explain. In which case we should explain it somewhere.

If the sole reason is the authors are unknown we should filter them out and replace them with an empty authorship. It is very fine to have them in the FishBase ACEF files and the Clearinghouse as it is the way they have it. But `Chaetodon rafflesii Anonymous [Bennett], 1830` [should not get into the CoL](http://www.catalogueoflife.org/col/details/species/id/c2ffd6445e04b8bf223d07f6886ac346)

**Comment by mdoering** [comment]
Does `Anonymous [Bennett], 1830` mean no author, but maybe Bennett? And surely published in 1830?

**Comment by mdoering** [comment]
from http://researcharchive.calacademy.org/research/ichthyology/catalog/getref.asp?id=259:

> Anonymous [Bennett], E. T.  1830 [ref. 259]
Most workers cite Bennett as author, but there is no internal evidence that he was the author. We treat Bennett as the anonymous author and place his name in brackets as required by the ICZN code, but we use the convention "Anonymous [Bennett] 1830".


And this is **ICZN Recommendation 51D**:
> Author anonymous, or anonymous but known or inferred. If the name of a taxon was (or is deemed to have been) established anonymously, the term "Anon." may be used as though it was the name of the authors. However, if the authorship is known or inferred from external evidence, the name of the author, if cited, should be enclosed in square brackets to show the original anonymity. For availability of names proposed anonymously see Article 14.

**Comment by yroskov** [comment]
There is no contradiction between Code and presentation in FishBase. CoL+ software must accommodate square brackets, etc. (Meaning of square brackets is obvious: https://www.google.com/search?client=firefox-b-1-d&channel=cus&ei=Pd9fXe6WCcHmsAWN57SICw&q=usage+of+square+brackets&oq=usage+of+square+&gs_l=psy-ab.1.0.0j0i22i30l9.1647.7130..9887...1.2..2.101.1346.20j1......0....1..gws-wiz.....10..0i71j35i39j0i131i20i263j0i131j0i131i67j0i67j0i10j0i22i10i30.KwFX-s8AgPE 
Metadata is not an universal solution. Very often metadata and comments are ignored when scientific names pass from taxonomic/nomenclatural resource to regional, ecological and other specialized  resources.
