### ISSUE TITLE
Update CoL diff tool

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-repo#39]
- [x] Create separate tests for common names, country, language and transliteration
- [x] Parse the latest taxonomic scrutiny date
- [x] Fix species URL bug
- [x] Fix parsing of database completeness and version
- [x] Reformat author strings like CoL+ so that formatting improvements aren't flagged

**Comment by gdower** [comment]
I excluded country, language and transliteration from the common_names tests for now because we mostly want to know if the common names are all there. I could add more sophisticated testing later if we want to check those other columns.

**Comment by mdoering** [comment]
country and language would be good to know if they differ. we found various little issues with them and I wouldnt be surprised to learn about more parsing problems

**Comment by gdower** [comment]
@mdoering Okay, I'll add in a check on language and country. I'll try to make them separate tests.

For taxonomic scrutiny dates, I'm thinking about just standardizing them all in AG+ to the YYYY-MM-DD standard rather than trying to parse a wide variety of date formats.

**Comment by mdoering** [comment]
if you can losslessly sure. I could expose our date parser as a service if you want to get started quickly. even with bulk requests taking lists if thats useful?
