### ISSUE TITLE
Investigate and fix broken sectors

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-repo#45]

**Comment by gdower** [comment]
There's 2 remaining [broken sectors](https://www.col.plus/sector/broken) in 3i Auchenorrhyncha (Tettigonia and Cicada), which seems to be a different issue. Here's the Kibana logs for [Tettigonia](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(columns:!(_source),index:AWyLa4mQHCKcR6PFXu4X,interval:auto,query:(query_string:(query:Tettigonia)),sort:!('@timestamp',desc))) and [Cicada]().

```
Fail to sync Sector{4932, datasetKey=1189, mode=ATTACH, code=null, subject=GENUS Tettigonia}: Sector 4932 does have a non existing subject GENUS Tettigonia for dataset 1189
```

```
Sector 4850 cannot be rematched to dataset 1189 - multiple names like GENUS Tettigonia
```

```
Fail to sync Sector{6105, datasetKey=1189, mode=ATTACH, code=null, subject=GENUS Cicada}: Sector 6105 does have a non existing subject GENUS Cicada for dataset 1189
```

```
Sector 5450 cannot be rematched to dataset 1189 - multiple names like GENUS Cicad
```

@yroskov investigated these sectors and it's caused by [Tettigonia](https://www.col.plus/dataset/1189/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&q=Tettigonia&rank=genus&sortBy=taxonomic) and [Cicada](https://www.col.plus/dataset/1189/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&q=Cicada&rank=genus&sortBy=taxonomic) appearing twice within the same GSD in different families, which might cause the sector matching problem. We'll ask Dmitry whether those are legal homonyms.

**Comment by mdoering** [comment]
Yes, homonyms/duplicates are a matching problem. We *could* tell the system to pick one randomly, but I'd rather prefer if those issues are manually resolved. Let's think about the best tools needed to do so. The rematch function returning a better message what actually was the problem is a start.

**Comment by mdoering** [comment]
Decisions and sectors currently do not use much the "advanced" feature to link to a source name. We mostly use:
 - name
 - rank
 - authorship

But there is also available but currently not used in the automaticly generated sectors:
 - status
 - code (botany, zoology, bacterial, virus)
 - parent (i.e. the parents name)

With parent for example we could resolve the homonyms in this case without relying on stable source ids

**Comment by mdoering** [comment]
For sure there cannot be 2 valid accepted Tettigonia genera in Zoology and even in practise not within Hemiptera alone.

**Comment by yroskov** [comment]
As Dmitry exlained, set of species from Tettigonia and Cicada have been moved to other families. New genera are not established for these species. Case of incertae sedis for species. Species should be attached directly to family in the classification:

[Tettigonia]
Family Cicadidae
chinensis • 3i Auchenorrhyncha
conspurcata • 3i Auchenorrhyncha
tenebricosa • 3i Auchenorrhyncha

[Cicada]
Family Cicadellidae
Cicada danais • 3i Auchenorrhyncha
Cicada frontalis • 3i Auchenorrhyncha
Cicada marginata • 3i Auchenorrhyncha
Cicada suturalis • 3i Auchenorrhyncha

**Comment by mdoering** [comment]
interesting. Maybe this a ACEF artifact when there is no explicit genus. That might have happened elsewhere too

**Comment by mdoering** [comment]
When I think about it again, is it good practise to do that? Should the binomial with the wrong genus really be used when the genus is classified differently elsewhere? Isn't it better to wait with the move to a new family until the new genus is established or the species have been recombined into another existing genus? It will confuse the hack out of many software and probably the minds of users too when they see a binomial with a genus that is not meant to be that genus.

**Comment by yroskov** [comment]
As a botanist I completely agree with you, Markus. But Dmitry, as a zoologist, has another opinion. If he would submit his unassigned species with empty genus field, CoL simply block those species from final product. But he used basionyms with unassigned species in his export to ACEF, and placed species in another family. CoL may chose one of 3 approaches: 1) accept species names without genus (it was never happened before), 2) allow "split" genera and mark "secondary" batch as Provisionally Accepted, 3) block "secondary" batch in final product [until taxonomists resolve the situation - might be never]. My choice is 3. What is yours?
