### ISSUE TITLE
ACEF#10 contains duplicate keys

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-repo#5]
The AcceptedSpecies record Fis-167416 exists twice in the archive which is illegal.
Looks like a duplication, either in original data or via sql joins?

```
Fis-167416	Animalia	Chordata	Actinopterygii	Beryciformes	\N	Holocentridae	Sargocentron	\N	suborbitale	(Gill, 1863)	\N	accepted name	0	0	1	marine@@@marine	Genus gender is neuter.	\N	01-Mar-2017	http://www.fishbase.org/Summary/SpeciesSummary.php?ID=13775	13775	167416
Fis-167416	Animalia	Chordata	Actinopterygii	Beryciformes	\N	Holocentridae	Sargocentron	\N	suborbitale	(Gill, 1863)	\N	accepted name	0	0	1	marine@@@marine	Genus gender is neuter.	\N	19-May-2014	http://www.fishbase.org/Summary/SpeciesSummary.php?ID=13775	13775	167416
```

**Comment by mdoering** [comment]
check for other datasets too:
https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:('$$hashKey':'object:833',display:'1%20minute',pause:!f,section:2,value:60000),time:(from:'2018-02-26T23:36:24.927Z',mode:absolute,to:'2018-02-28T22:59:59.999Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWBa0XR-f8lu3pmE7ete,key:environment,negate:!f,type:phrase,value:col),query:(match:(environment:(query:col,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:level,negate:!f,type:phrase,value:ERROR),query:(match:(level:(query:ERROR,type:phrase))))),index:AWGthDPVf8lu3pmEwvFE,interval:auto,query:(query_string:(query:'%22TaxonID%20values%20not%20unique%22')),sort:!('@timestamp',desc))

**Comment by ayco-at-naturalis** [comment]
No, it really is a duplicate (same original id; different database ids)

**Comment by mdoering** [comment]
both ACEF and dwca require unique ids, we need to alter or filter them out

**Comment by ayco-at-naturalis** [comment]
In that case we must discuss how to proceed. The assembly database is far from clean. If the ACEF import requires that the data in the zip files are clean and valid, we cannot do with just a simple bash script and SQL script. After all, there's a big data conversion program, written by Ruud, that converts the assembly database to the base schema and does a lot of cleanup along the road.

**Comment by mdoering** [comment]
It doesnt have to be clean in all apsects. It is only unique primary keys that are required. We could losen that too, but should we? GBIF is strict on this with DwC-A and no dataset without unique keys goes in

**Comment by mdoering** [comment]
ok ,lets losen the unique constraint in imports

**Comment by mdoering** [comment]
the dataset also contains distributions linked to non existing taxa:

> Non existing taxonID Fis-153593 found in Distribution record line 7499, Distribution.txt
