### ISSUE TITLE
Escape line breaks in ACEF

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-repo#6]
they can exist anywhere, but especially the datasource file is vulnerable and known to contain linebreaks, e.g. datasource 101

Convert any of \t \n or \r to simple spaces!

**Comment by mdoering** [comment]
might also be the cause of "Distribution.txt skip line 3750 with too few columns (found 3, expected 4)" in dataset 10: https://logs.gbif.org/app/kibana#/doc/AWGthDPVf8lu3pmEwvFE/col-admin-server-2018.02.27/logs?id=AWHXXL7yf8lu3pmEe64G&_g=(refreshInterval:('$$hashKey':'object:827',display:'30%20seconds',pause:!f,section:1,value:30000),time:(from:'2018-02-27T13:00:00.000Z',mode:absolute,to:'2018-02-28T22:59:59.999Z'))

**Comment by mdoering** [comment]
or alternatively use proper CSV with commas and quoted values that allow multilines. But then the double quote character needs escaped...

**Comment by mdoering** [comment]
@ayco-at-naturalis can we close this?

**Comment by ayco-at-naturalis** [comment]
It seems like MySQL's SELECT INTO OUTFILE does not generate valid CSV. At least not according to https://tools.ietf.org/html/rfc4180. Even/especially (!) when adding a character escaping instruction. It will not only escape the escape character and the enclosure character, but also (completely unnecessarily) the end-of-record character. See https://dev.mysql.com/doc/refman/5.7/en/select-into.html. You actually see this happening in Distribution.txt.

Thus indeed we must use the SQL REPLACE function to convert any of \t \n or \r to simple spaces!

REPLACE(REPLACE(REPLACE(REPLACE(IFNULL(distribution, ''), '\r\n', ' '), '\n', ' '), '\r', ' '), '\t', ' ')

We should probably does this only for columns we can faintly expect to contain those characters :

1. distribution.distribution
2. scientific_names.comment
3. references.title
4. references.source
5. references.author
6. common_names.common_name
7. common_names.area

**Comment by ayco-at-naturalis** [comment]
Added lifezone even though in the current edition it does not contain those characters

**Comment by ayco-at-naturalis** [comment]
Added scientific_names.author
