### ISSUE TITLE
col_diff_misses

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-repo#60]
In trying to resolve the URLs between different editions of CoL without name_codes (see https://github.com/Sp2000/colplus-backend/issues/470), I was unable to resolve 1349 names and the output from that is [here](https://docs.google.com/spreadsheets/d/1BC0O5-zCJ7Ndl1SNUcZS2lPy1yT-jVAi-XzozzV-nzg/edit#gid=2013132535).

**Comment by gdower** [comment]
@yroskov, this is interesting:

diff_key | hierarchy | p8 | p7 | p6 | p5 | p4 | p3 | p2 | p1 | name | hash | url
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
e22ccb1be7cfa9842320c78e2a524153 | Animalia_Arthropoda_Diplopoda_Polydesmida_Trichopolydesmoidea_Not assigned_Moojenodesmus_Moojenodesmus irmgardae |   | Animalia | Arthropoda | Diplopoda | Polydesmida | Trichopolydesmoidea | Not assigned | Moojenodesmus | Moojenodesmus irmgardae | 2abae75bb571644054fadbfd78b731fa | http://workbench.catalogueoflife.org/col_plus/details/species/id/2abae75bb571644054fadbfd78b731fa
5699c23906721e3b6ae2d7ea577b115d | Animalia_Arthropoda_Diplopoda_Polydesmida_Not assigned_Moojenodesmus_Moojenodesmus irmgardae |   |   | Animalia | Arthropoda | Diplopoda | Polydesmida | Not assigned | Moojenodesmus | Moojenodesmus irmgardae | 2abae75bb571644054fadbfd78b731fa | http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/2abae75bb571644054fadbfd78b731fa

**Comment by yroskov** [comment]
I can find only single entry in order Polydesmida in the production interface.

**Comment by gdower** [comment]
@mdoering @yroskov, I found the problem. I need to update my local ac_latest. I'll post a new report once I get that done.
