### ISSUE TITLE
MOSS Tropicos - 67.586 invalid reference ids 

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-repo#73]
https://www.col.plus/dataset/1019/issues

https://www.col.plus/dataset/1019/verbatim?issue=reference%20id%20invalid

**Comment by gdower** [comment]
The database_id in Assembly_Global is NULL, which is [likely the problem](https://github.com/Sp2000/colplus-repo/blob/master/ACEF/script/assembly_db_to_acef.sql#L184). ScaleNet has the same problem.

I'll regenerate those ACEF archives.

**Comment by mdoering** [comment]
btw, just talked to MOSS Tropicos and we'll get a shiny new version soon
