### ISSUE TITLE
TaxonWorks CoLDP exporter

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-repo#76]
From meeting with Tommy McElrath, below are potential bugs in either CoL+ or TaxonWorks exporter. I'll investigate these issues further and open bug tickets in the appropriate repos.

- [x] All synonyms might be getting listed as accepted names (TaxonWorks bug?)
  - Rhyzophagus Gyllenhal, 1813 and Ryzophagus Herbst, 1793 are synonyms not accepted names
- [x] Synonyms ranked as species or lower might be getting assigned to the parent uninomial instead of the species or lower rank accepted name (TaxonWorks bug?)
- [x] Synonyms with the same exact scientific name but different name relations might be getting counted as duplicates (CoL+ bug?)
- [x] There might be duplicate references including duplicate reference IDs (TaxonWorks bug?)
- [x] [Mispelled names have [sic] appended to the end which isn't parsed by CoL+](https://dev.col.plus/dataset/2061/verbatim?issue=partially%20parsable%20name). Maybe CoL+ should move [sic] to appendedPhrase, or maybe TaxonWorks should put [sic] in appendedPhrase.
- [x] The very top uninomials in the dataset have no parents so get flagged with the issue "Parent Id Invalid"
- [x] When hitting the browser back button the classification tree does not fully expand to the previous state (CoL+ frontend bug)

**Comment by mdoering** [comment]
[[sic]](https://github.com/gbif/name-parser/issues/33) is a known problem we will fix soon in CoL+

**Comment by gdower** [comment]
@mdoering, I guess [we never decided on a way to register top level uninomials so that they aren't flagged as parent ID invalid](https://github.com/Sp2000/colplus-backend/issues/240)? In this case it's actually a TaxonWorks exporter bug because it assigned them parent ID 85906, which doesn't exist in the export. Should parentID just be left empty?

**Comment by mdoering** [comment]
yes, parentID should simply be left empty if it does not have a parent but is considered root

**Comment by gdower** [comment]
I think name relations are not causing duplicates, but instead it's the TaxonWorks exporter bug that is attaching the same synonym to multiple higher taxa. So I think this is not actually an issue, but I'll keep an eye out for it when we get that other issue resolved:

> Synonyms with the same exact scientific name but different name relations might be getting counted as duplicates (CoL+ bug?)
