### ISSUE TITLE
ACEF#130 Non existing W-Msc-577125

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-repo#8]
Non existing AcceptedTaxonID "W-Msc-577125" found in CommonNames record line 7017, CommonNames.txt of ACEF dataset 130

Is that genuine like this in the assembly db?

**Comment by ayco-at-naturalis** [comment]
No, there **is** a record in AcceptedSpecies.txt (line 34702) with this AcceptedTaxonID

**Comment by ayco-at-naturalis** [comment]
The common name itself though is bogus:  "????????"

**Comment by ayco-at-naturalis** [comment]
Hmmm ...  we have a lot of those "bogus names", but I think it's actually a UTF8 problem

**Comment by mdoering** [comment]
If the name is like that leave it, we dont need to cleanup existing bad data here.
Smelled like bad relations or missing records. But if thats not the case please just close

**Comment by mdoering** [comment]
ah, in that case its different. If it is a character encoding problem. What does the actual CoL website say about these names? Are they shown correctly there? That should be our reference

**Comment by ayco-at-naturalis** [comment]
They show up correctly there, so I'll check the mysql dump file used to create the assembly db (at my machine)

**Comment by ayco-at-naturalis** [comment]
It turned out not to be an issue but threw up a utf8 problem which is now solved
