### ISSUE TITLE
Write script to upload GSD logos to Clearinghouse

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-repo#81]

**Comment by gdower** [comment]
Re: https://github.com/Sp2000/ConversionTool/issues/15#issuecomment-551133993

**Comment by mdoering** [comment]
https://github.com/Sp2000/col-info-pages-settings/tree/master/images/databases

**Comment by mdoering** [comment]
probably not needed, I have added them to the [repo](https://github.com/Sp2000/colplus-repo/tree/master/logos) and will include their URL to the dataset.sql file when wiping

**Comment by mdoering** [comment]
we just might miss a few that need to be adjusted manually
