### ISSUE TITLE
Missing logos

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-repo#83]
2 logos are missing:

 - https://github.com/Sp2000/colplus-repo/raw/master/logos/StaphBase.png
 - https://github.com/Sp2000/colplus-repo/raw/master/logos/Ginkgoales.png

Should be uploaded either manually after we keep prod or placed here:
https://github.com/Sp2000/colplus-repo/tree/master/logos

**Comment by gdower** [comment]
I uploaded the missing logos to the Clearinghouse, which should fix the issue on the next conversion **after** 2020-01-08.
