### ISSUE TITLE
ACEF#15 bad NULL values

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-repo#9]
files from acef#15 seem to contain badly encoded null values that break the quoted CSV format in use. Example from CommonName.txt with the Area and ReferenceID values badly quoted, missing an end quote for the N value (if that actually is a meaningful value at all?):

```
"AcceptedTaxonID","CommonName","TransliteratedNames","Language","Country","Area","ReferenceID"
"ILD-158","Guannegoul","","","","N," ILD-2157"
"ILD-1407","Wild Lucerne","","English","","N," ILD-3030"
```

Also the space in front of the referenceID looks wrong. Does that represent the real data?

**Comment by mdoering** [comment]
reference "ILD-3402" is missing from the archive, but referred to a lot from thousands of places. Is that correct?

**Comment by ayco-at-naturalis** [comment]
created mysql function to deal with whitespace
