### ISSUE TITLE
Update nomenclatural codes for all CoL datasets and sectors

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-repo#98]
Knowing the nomenclatural code helps to better parse and render names.
As part of the editorial process we should always make sure datasets are assigned the code their data is restricted to. For datasets covering multiple codes the code should be configured in the sectors (see screenshot)

<img width="997" alt="Bildschirmfoto 2019-12-19 um 17 03 34" src="https://user-images.githubusercontent.com/327505/71188637-9b4f1c00-2281-11ea-82d5-6c3ad94a7159.png">

**Comment by gdower** [comment]
I added a [script to declare the nomenclatural codes for all GSDs](https://github.com/gdower/colplus-data-tools/blob/master/declare_code.py) except for a few that use a hybrid nomenclatural codes between zoological and botanical. Also, there's a [script to declare the nomenclatural codes by sector for ITIS](https://github.com/gdower/colplus-data-tools/blob/master/declare_code_itis_sectors.py). The code declarations have been applied to prod.
