### ISSUE TITLE
Small assembly on dev 2019-12-23

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-repo#99]
@yroskov  and I created a small assembly on dev to test the verbatim author strings, vernacular names, and [sporadically missing infraspecies](https://github.com/Sp2000/ConversionTool/issues/21) issues. Assembly included Scarabs, ScaleNet, the genus Geranium, and viruses as [export-2049.zip](https://github.com/Sp2000/colplus-repo/files/3995746/export-2049.zip).

Frontend version: 8dcd15b December 20, 2019 4:19 PM
Backend version: d504345 December 21, 2019 10:52 AM

**Comment by yroskov** [comment]
Tests of conversion **Catalogue of Life: 2019-12-23** at http://workbench.catalogueoflife.org/col_plus/browse/tree?4f2968507872a303c8617198cb6c4d41 
with **5 sample datasets from FishBase (class Cephalaspidomorphi), ScaleNet, Scarabs, RJB Geranium & ICTV_MSL.**

**FishBase (class Cephalaspidomorphi)** 
Acc spp: 47 = 47
Species page for _Eudontomyzon mariae_ (http://workbench.catalogueoflife.org/col_plus/details/species/id/15692771d88933f2fbac9ee05f323459) = no missing name, no missing references, no missing common names, encoding OK, classification OK, distribution as a text OK, environment OK, add data OK, LTS OK, source database OK, 
**Missing authorstrings in misapplied names:**
Master view:
Eudontomyzon stankokaramani **(non Karaman, 1974)** (misapplied name) 
Eudontomyzon vladykovi stankokaramani **(non Karaman, 1974)** (misapplied name) 
Petromyzon branchialis **(non Linnaeus, 1758)** (misapplied name)
CoL+ view:
Eudontomyzon stankokaramani (misapplied name) 
Eudontomyzon vladykovi stankokaramani (misapplied name) 
Petromyzon branchialis (misapplied name)
**Bibliographic citation needs adjustment:** Froese R. & Pauly D. (eds). (2019). FishBase (version Feb 2018). In: **Draft** Catalogue of Life, 2019-12-23 **()**. Digital resource at www.catalogueoflife.org/col. Species 2000: Naturalis, Leiden, the Netherlands. ISSN 2405-8858.

**ScaleNet**
All stats matched, except common names 1,725 (master) vs 1,676 (CoL+) = 49 names consolidated 
Species page for _Abgrallaspis cyanophylli_ (http://workbench.catalogueoflife.org/col_plus/details/species/id/1f8a2a9d1f5057efa8ec0ea187a16fbb) = all fields are OK as above.

**Scarabs**
All stats OK
Species page for _Osmoderma eremita_ (http://workbench.catalogueoflife.org/col_plus/details/species/id/442d9545343c9943e761f5d1d77fcd24/synonym/436b89de3526b337df77c59ec9213164) = all fields are OK as above.

**RJB Geranium**
All stats OK
Species page for _Geranium pretense_ (http://workbench.catalogueoflife.org/col_plus/details/species/id/2ad094d4c1dc667caaa294a17d32a27e) = all fields are OK as above.

**ICTV_MSL**
All stats OK
Species page for _Carlavirus Garlic common latent virus_ (http://workbench.catalogueoflife.org/col_plus/details/species/id/96cfdc38bac470b60f73accca409262a) = all fields are OK.
